"""Added stored credential model

Revision ID: 2f5874563663
Revises: None
Create Date: 2013-01-12 17:16:22.974322

"""

# revision identifiers, used by Alembic.
revision = '2f5874563663'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_credentials',
    sa.Column('school', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('encrypted_password', sa.LargeBinary(length=255), nullable=False),
    sa.PrimaryKeyConstraint('school', 'username')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_credentials')
    ### end Alembic commands ###
